name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm ci

      - name: Build web application
        run: npm run build

      - name: Install Electron dependencies
        working-directory: electron-erp-app
        run: npm ci

      - name: Build Electron application
        working-directory: electron-erp-app
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create dist.zip
        run: |
          Compress-Archive -Path dist/* -DestinationPath dist.zip
        shell: pwsh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            electron-erp-app/dist/*.exe
            electron-erp-app/dist/latest.yml
            dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
