name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm ci

      - name: Build web application
        run: npm run build

      - name: Copy dist to Electron app
        run: |
          if not exist "electron-erp-app\resources\dist" mkdir "electron-erp-app\resources\dist"
          xcopy /E /I /Y "dist\*" "electron-erp-app\resources\dist\"
        shell: cmd

      - name: Install Electron dependencies
        working-directory: ./electron-erp-app
        run: npm ci

      - name: Build Electron application
        working-directory: ./electron-erp-app
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
